http:
  enabled: true
  port: 8391

minepos-link: https://demo.minepos.net/
API-KEY: 123

#If the player needs to be online for the order to process the commands, we recommend this is set to true.
#If the player is not online MinePoS will await the player coming online to run the commands
#If the server is restarted with out running the commands MinePoS will fetch and queue the commands upcon start
need-player-online: true

guis:
  main: "gui/main.yml"
  other:
commands:
  base-commands:
  - minepos
  - buy
  base-command-description: "MinePoS Base Command"